baseURL = 'https://solmyrath.vercel.app/'
languageCode = 'fr'
title = 'Solmyrath'
theme = 'hugo-book'

disablePathToLower = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'base16-snazzy'

[imaging]
  quality = 80
  resampleFilter = "Lanczos"
  hint = "photo"

[imaging.exif]
  disableLatLong = true

[params]
  BookTheme = 'auto'
  BookSection = 'docs'
  BookToC = true
  BookSearch = true
  BookComments = false
  BookPortableLinks = 'warning'
  BookDateFormat = '2 January 2006'
